import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BedDouble,
  Blocks,
  Bot,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Compass,
  Database,
  FileSpreadsheet,
  FileStack,
  FolderOpen,
  GraduationCap,
  HardHat,
  HeartHandshake,
  House,
  LayoutGrid,
  Layers,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Package,
  PartyPopper,
  Phone,
  Play,
  PlayCircle,
  RefreshCw,
  ScanLine,
  Scale,
  Search,
  Send,
  Settings2,
  Shapes,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Truck,
  Upload,
  UserCog,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";

/**
 * Registro delle icone usate nel sito.
 * Elenco esplicito invece di import dinamico: il bundle resta piccolo
 * e un nome sbagliato si nota subito perché l'icona non compare.
 */
const registro = {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BedDouble,
  Blocks,
  Bot,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Compass,
  Database,
  FileSpreadsheet,
  FileStack,
  FolderOpen,
  GraduationCap,
  HardHat,
  HeartHandshake,
  House,
  LayoutGrid,
  Layers,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Package,
  PartyPopper,
  Phone,
  Play,
  PlayCircle,
  RefreshCw,
  ScanLine,
  Scale,
  Search,
  Send,
  Settings2,
  Shapes,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Truck,
  Upload,
  UserCog,
  Users,
  Wrench,
  X,
  Zap,
};

/**
 * @param {{nome: string, className?: string, strokeWidth?: number}} props
 */
export default function Icona({ nome, className = "size-5", strokeWidth = 1.75 }) {
  const Componente = registro[nome] || Shapes;
  return <Componente className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
